### ISSUE TITLE
你好，我想问训练集中实体数量为什么和我下载的数据集中实体数量不同呢

### ISSUE THREAD

**Issue by shencunzailaozhang** [fordai/CCKS2019_Chinese_Clinical_NER#5]
同样是1000条训练集，我下载的数据集中每一类型的实体数量都远超你的实体数量，请问你的数据集构成是这样的吗？
![image](https://user-images.githubusercontent.com/35827282/100348705-3d46bf00-3022-11eb-9686-de7aeda47bef.png)

**Comment by fordai** [comment]
数据集构成相同，其统计信息由CCKS2019官方提供。
