### ISSUE TITLE
I am trying to rebuild your ner model with HK financial news corpus and my own pre-trained w2v model

### ISSUE THREAD

**Issue by marcusau** [fordai/CCKS2019_Chinese_Clinical_NER#6]
Thanks for your contribution. 

I am trying to rebuild your NER model with my own set of corpus and word2vec pretrained models.

My own corpus was built by financial news journals produced in HK and all are written in traditional Chinese

Thanks a lot.

**Comment by fordai** [comment]
That's good, and I do suggest you to try some more advanced models, especially the BERT-BiLSTM-CRF model, i.e., the current baseline model for NER.
