### ISSUE TITLE
CCKS2019-Chinese-Clinical-NER 数据集

### ISSUE THREAD

**Issue by wangxuan123123** [fordai/CCKS2019_Chinese_Clinical_NER#9]
作者好，请问数据集可以通过邮件分享一下吗，现在比赛截止了，官网上数据集找不到了。我的邮箱是952439580@qq.com，保证不会随意传播，不会用于科研之外的用途，十分感谢！

**Comment by fordai** [comment]
可以通过报名参加CCKS2021获取数据集。
